substitutions:
  name: m5stack-atom-echo-bbc74c
  friendly_name: M5Stack Atom Echo bbc74c
packages:
  m5stack.atom-echo-wake-word-voice-assistant: github://esphome/wake-word-voice-assistants/m5stack-atom-echo/m5stack-atom-echo.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  min_version: 2025.5.0
api:
  encryption:
    key: Y8k52K6Lm6Tg0ULLjM6jx2hkCn7WXn7M0zC9cKi6oug=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
